In [1]:
import numpy as np

In [2]:
#Numpy : Array manipulation

In [4]:
arr = np.random.randint(1,10,(4,4))

In [5]:
arr

array([[1, 4, 6, 6],
       [3, 7, 8, 3],
       [8, 6, 1, 5],
       [8, 8, 1, 7]])

In [6]:
arr.reshape(8,2)

array([[1, 4],
       [6, 6],
       [3, 7],
       [8, 3],
       [8, 6],
       [1, 5],
       [8, 8],
       [1, 7]])

In [7]:
arr.T

array([[1, 3, 8, 8],
       [4, 7, 6, 8],
       [6, 8, 1, 1],
       [6, 3, 5, 7]])

In [8]:
arr.flatten()

array([1, 4, 6, 6, 3, 7, 8, 3, 8, 6, 1, 5, 8, 8, 1, 7])

In [9]:
arr

array([[1, 4, 6, 6],
       [3, 7, 8, 3],
       [8, 6, 1, 5],
       [8, 8, 1, 7]])

In [10]:
np.expand_dims(arr,axis=1)

array([[[1, 4, 6, 6]],

       [[3, 7, 8, 3]],

       [[8, 6, 1, 5]],

       [[8, 8, 1, 7]]])

In [11]:
np.expand_dims(arr, axis=0)

array([[[1, 4, 6, 6],
        [3, 7, 8, 3],
        [8, 6, 1, 5],
        [8, 8, 1, 7]]])

In [12]:
data = np.array([[1],[2],[3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [15]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [17]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
#Numpy: Binary operation

In [19]:
arr1 = np.random.randint(1,10, (3,4))
arr2 = np.random.randint(1,10, (3,4))

In [20]:
arr1

array([[9, 3, 1, 8],
       [2, 8, 1, 7],
       [8, 5, 8, 2]])

In [21]:
arr2

array([[1, 2, 2, 8],
       [6, 3, 2, 9],
       [5, 3, 2, 8]])

In [22]:
arr1+arr2

array([[10,  5,  3, 16],
       [ 8, 11,  3, 16],
       [13,  8, 10, 10]])

In [23]:
arr1/arr2

array([[9.        , 1.5       , 0.5       , 1.        ],
       [0.33333333, 2.66666667, 0.5       , 0.77777778],
       [1.6       , 1.66666667, 4.        , 0.25      ]])

In [24]:
arr1-arr2

array([[ 8,  1, -1,  0],
       [-4,  5, -1, -2],
       [ 3,  2,  6, -6]])

In [25]:
arr1**arr2

array([[       9,        9,        1, 16777216],
       [      64,      512,        1, 40353607],
       [   32768,      125,       64,      256]])

In [26]:
-arr1

array([[-9, -3, -1, -8],
       [-2, -8, -1, -7],
       [-8, -5, -8, -2]])

In [27]:
-(-arr1)

array([[9, 3, 1, 8],
       [2, 8, 1, 7],
       [8, 5, 8, 2]])

In [28]:
arr1>arr2

array([[ True,  True, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [29]:
#numpy; Stringoperations

In [30]:
arr = np.array(["Sumit","Kumar"])

In [31]:
arr

array(['Sumit', 'Kumar'], dtype='<U5')

In [32]:
np.char.upper(arr)

array(['SUMIT', 'KUMAR'], dtype='<U5')

In [33]:
np.char.capitalize(arr)

array(['Sumit', 'Kumar'], dtype='<U5')

In [34]:
np.char.title(arr)

array(['Sumit', 'Kumar'], dtype='<U5')

In [35]:
#Numpy: Mathematical operation

In [36]:
arr1

array([[9, 3, 1, 8],
       [2, 8, 1, 7],
       [8, 5, 8, 2]])

In [38]:
np.sin(arr1)

array([[ 0.41211849,  0.14112001,  0.84147098,  0.98935825],
       [ 0.90929743,  0.98935825,  0.84147098,  0.6569866 ],
       [ 0.98935825, -0.95892427,  0.98935825,  0.90929743]])

In [39]:
np.tan(arr1)

array([[-0.45231566, -0.14254654,  1.55740772, -6.79971146],
       [-2.18503986, -6.79971146,  1.55740772,  0.87144798],
       [-6.79971146, -3.38051501, -6.79971146, -2.18503986]])

In [40]:
np.log10(arr1)

array([[0.95424251, 0.47712125, 0.        , 0.90308999],
       [0.30103   , 0.90308999, 0.        , 0.84509804],
       [0.90308999, 0.69897   , 0.90308999, 0.30103   ]])

In [41]:
np.exp(arr1)

array([[8.10308393e+03, 2.00855369e+01, 2.71828183e+00, 2.98095799e+03],
       [7.38905610e+00, 2.98095799e+03, 2.71828183e+00, 1.09663316e+03],
       [2.98095799e+03, 1.48413159e+02, 2.98095799e+03, 7.38905610e+00]])

In [42]:
np.power(arr1,2)

array([[81,  9,  1, 64],
       [ 4, 64,  1, 49],
       [64, 25, 64,  4]])

In [43]:
arr1

array([[9, 3, 1, 8],
       [2, 8, 1, 7],
       [8, 5, 8, 2]])

In [44]:
np.mean(arr1)

5.166666666666667

In [45]:
np.median(arr1)

6.0

In [46]:
np.mode(arr1)

AttributeError: module 'numpy' has no attribute 'mode'

In [47]:
np.std(arr1)

3.0230595245361758

In [48]:
np.var(arr1)

9.13888888888889

In [49]:
np.min(arr1)

1

In [50]:
np.max(arr1)

9

In [51]:
#numpy : Airthmatic operation

In [52]:
arr1

array([[9, 3, 1, 8],
       [2, 8, 1, 7],
       [8, 5, 8, 2]])

In [53]:
arr2

array([[1, 2, 2, 8],
       [6, 3, 2, 9],
       [5, 3, 2, 8]])

In [54]:
arr1-arr2

array([[ 8,  1, -1,  0],
       [-4,  5, -1, -2],
       [ 3,  2,  6, -6]])

In [55]:
np.subtract(arr1,arr2)

array([[ 8,  1, -1,  0],
       [-4,  5, -1, -2],
       [ 3,  2,  6, -6]])

In [56]:
np.multiply(arr1,arr2)

array([[ 9,  6,  2, 64],
       [12, 24,  2, 63],
       [40, 15, 16, 16]])

In [57]:
np.mod(arr1,arr2)

array([[0, 1, 1, 0],
       [2, 2, 1, 7],
       [3, 2, 0, 2]])

In [58]:
np.power(arr1, arr2)

array([[       9,        9,        1, 16777216],
       [      64,      512,        1, 40353607],
       [   32768,      125,       64,      256]])

In [59]:
np.sqrt(arr1)

array([[3.        , 1.73205081, 1.        , 2.82842712],
       [1.41421356, 2.82842712, 1.        , 2.64575131],
       [2.82842712, 2.23606798, 2.82842712, 1.41421356]])

In [60]:
np.mean(arr1)

5.166666666666667

In [61]:
np.std(arr1)

3.0230595245361758

In [62]:
np.median(arr1)

6.0