In [1]:
import numpy as np

In [2]:
#Sort, search & counting function

In [6]:
arr = np.array([4,2,3,4,5,4,65,6,7,89,76,51])

arr

In [7]:
np.sort(arr)

array([ 2,  3,  4,  4,  4,  5,  6,  7, 51, 65, 76, 89])

In [8]:
np.searchsorted(arr,6)

6

In [13]:
arr1= np.array([0,324,543,65,7,8,9,0,0,0,0,0,9,345])

In [15]:
np.count_nonzero(arr1)

8

In [20]:
np.where(arr1 > 0)

(array([ 1,  2,  3,  4,  5,  6, 12, 13]),)

In [26]:
np.extract(arr1>2,arr1)

array([324, 543,  65,   7,   8,   9,   9, 345])

In [23]:
#Numpy- Byte Swaping

In [24]:
arr1

array([  0, 324, 543,  65,   7,   8,   9,   0,   0,   0,   0,   0,   9,
       345])

In [27]:
arr1.byteswap()

array([                  0, 4900197869555810304, 2234348365129187328,
       4683743612465315840,  504403158265495552,  576460752303423488,
        648518346341351424,                   0,                   0,
                         0,                   0,                   0,
        648518346341351424, 6413407344352296960])

In [29]:
arr.byteswap()

array([ 288230376151711744,  144115188075855872,  216172782113783808,
        288230376151711744,  360287970189639680,  288230376151711744,
       4683743612465315840,  432345564227567616,  504403158265495552,
       6413125869375586304, 5476377146882523136, 3674937295934324736])

In [30]:
#numpy: Copies & Views

In [31]:
arr1

array([  0, 324, 543,  65,   7,   8,   9,   0,   0,   0,   0,   0,   9,
       345])

In [33]:
a = np.copy(arr1)

In [34]:
b = arr1.view()

In [35]:
b

array([  0, 324, 543,  65,   7,   8,   9,   0,   0,   0,   0,   0,   9,
       345])

In [36]:
a

array([  0, 324, 543,  65,   7,   8,   9,   0,   0,   0,   0,   0,   9,
       345])

In [37]:
b[0]= 234

In [38]:
b

array([234, 324, 543,  65,   7,   8,   9,   0,   0,   0,   0,   0,   9,
       345])

In [39]:
arr1

array([234, 324, 543,  65,   7,   8,   9,   0,   0,   0,   0,   0,   9,
       345])

In [40]:
#Numpy matrix library

In [41]:
import numpy.matlib  as nm

In [42]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [44]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [45]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [46]:
#Numpy : Linear alzebra

In [47]:
arr1

array([234, 324, 543,  65,   7,   8,   9,   0,   0,   0,   0,   0,   9,
       345])

In [49]:
arr1=np.random.randint([[2,3],[4,5]])

In [50]:
arr2=np.random.randint([[2,3],[4,5]])

In [51]:
arr1

array([[0, 2],
       [1, 1]])

In [52]:
arr2

array([[0, 0],
       [0, 1]])

In [53]:
np.dot(arr1,arr2)

array([[0, 2],
       [0, 1]])

In [54]:
arr1@arr2

array([[0, 2],
       [0, 1]])