In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [2]:
arr = np.ones((3,4))

In [6]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [8]:
import pandas as pd

In [13]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
arr1 = np.eye(5)

In [12]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
arr2 = np.random.randint(1,5,(3,4))

In [15]:
arr2

array([[4, 2, 3, 3],
       [4, 4, 1, 3],
       [4, 4, 1, 1]])

In [16]:
arr2.size

12

In [17]:
arr2.shape

(3, 4)

In [18]:
arr2.reshape(4,3)

array([[4, 2, 3],
       [3, 4, 4],
       [1, 3, 4],
       [4, 1, 1]])

In [19]:
arr2.reshape(2,2,3)

array([[[4, 2, 3],
        [3, 4, 4]],

       [[1, 3, 4],
        [4, 1, 1]]])

In [20]:
arr2.reshape(4,-1)

array([[4, 2, 3],
       [3, 4, 4],
       [1, 3, 4],
       [4, 1, 1]])

In [26]:
arr2.reshape(2,2,1,1,3,1,1)

array([[[[[[[4]],

           [[2]],

           [[3]]]]],




        [[[[[3]],

           [[4]],

           [[4]]]]]],





       [[[[[[1]],

           [[3]],

           [[4]]]]],




        [[[[[4]],

           [[1]],

           [[1]]]]]]])

In [5]:
arr1 = np.random.randint(1,10, (5,6))

In [28]:
arr1

array([[1, 1, 6, 9, 9, 9],
       [7, 2, 1, 3, 4, 6],
       [5, 3, 7, 7, 8, 5],
       [1, 6, 8, 1, 5, 7],
       [7, 9, 9, 4, 2, 5]])

In [29]:
arr1>5

array([[False, False,  True,  True,  True,  True],
       [ True, False, False, False, False,  True],
       [False, False,  True,  True,  True, False],
       [False,  True,  True, False, False,  True],
       [ True,  True,  True, False, False, False]])

In [30]:
arr1[arr1>8]

array([9, 9, 9, 9, 9])

In [31]:
arr1

array([[1, 1, 6, 9, 9, 9],
       [7, 2, 1, 3, 4, 6],
       [5, 3, 7, 7, 8, 5],
       [1, 6, 8, 1, 5, 7],
       [7, 9, 9, 4, 2, 5]])

In [32]:
arr1[0]

array([1, 1, 6, 9, 9, 9])

In [34]:
arr1[0,[0,1]]

array([1, 1])

In [35]:
arr1[0,[0,4]]

array([1, 9])

In [36]:
arr1[1,[0,4]]

array([7, 4])

In [37]:
arr1[2:4,[2,4]]

array([[7, 8],
       [8, 5]])

In [38]:
arr1 = np.random.randint(1,3, (3,3))
arr2 = np.random.randint(1,3, (3,3))


In [39]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [2, 2, 1]])

In [40]:
arr2

array([[2, 1, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [41]:
arr1 + arr2

array([[4, 2, 3],
       [3, 3, 3],
       [4, 3, 2]])

In [42]:
arr1*arr2

array([[4, 1, 2],
       [2, 2, 2],
       [4, 2, 1]])

In [43]:
(arr1+2)*(arr2+7)

array([[36, 24, 27],
       [27, 27, 32],
       [36, 32, 24]])

In [44]:
arr1@arr2

array([[ 8,  5,  6],
       [ 8,  5,  5],
       [10,  7,  7]])

In [45]:
arr1/arr2

array([[1. , 1. , 0.5],
       [0.5, 0.5, 2. ],
       [1. , 2. , 1. ]])

In [46]:
arr1/0

/tmp/ipykernel_110/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [47]:
#numpy : Broadcasting

In [6]:
arr = np.zeros((3,4))

In [7]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
a = np.array([1,2,3,4])

In [9]:
a

array([1, 2, 3, 4])

In [10]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [14]:
b = np.array([[3,4,5]])

In [15]:
b

array([[3, 4, 5]])

In [17]:
arr+b

ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 

In [16]:
b.T

array([[3],
       [4],
       [5]])

In [19]:
arr1= arr+b.T

In [20]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [21]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [22]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [23]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [24]:
np.min(arr1)

3.0

In [25]:
np.max(arr1)

5.0